name: "Track TODO Action"
description: "Sync TODO/BUG/FIXME comments with GitHub Issues and Projects"
author: "Taras Kushnir"
inputs:
  REPO:
    description: "Repository"
    default: "${{ github.repository }}"
  TOKEN:
    description: "Github token"
  INCLUDE_PATTERN:
    description: "Regexp for source files to include"
    default: ""
  EXCLUDE_PATTERN:
    description: "Regexp for source files to exclude"
    default: ""
  ROOT:
    description: "Root directory for source code"
    default: "."
  MIN_WORDS:
    description: "Minimum amount of words to create an issue"
    default: "3"
  MIN_CHARACTERS:
    description: "Minimum amount of characters to create an issue"
    default: "30"
  DRY_RUN:
    description: "Do not create or close real issues"
    default: ""
  CLOSE_ON_SAME_BRANCH:
    description: "Close issues only if they are missing on the same branch"
    default: "1"
  ADD_LIMIT:
    description: "Limit number of issues to create during workflow"
    default: ""
  CLOSE_LIMIT:
    description: "Limit number of issues to close during workflow"
    default: ""
  LABEL:
    description: "Label to add for new issues"
    default: "todo comment"
  SHA:
    description: "SHA value of the commit"
    default: "${{ github.sha }}"
  REF:
    description: "Github Ref that triggered the workflow (branch or tag)"
    default: "${{ github.ref }}"
  EXTENDED_LABELS:
    description: "Create additional labels to mark branch, issue type etc."
    default: "1"
  PROJECT_COLUMN_ID:
    description: "ID of the project column to move newly created issues to"
    default: "-1"
  COMMENT_ON_ISSUES:
    description: "Create commit reference in the comments before closing the issue"
    default: "0"
  ACTION_ASSET_URL:
    description: 'Action binary to download'
    default: 'https://github.com/ribtoks/tdg-github-action/releases/latest/download/action.tar.gz'
runs:
  using: "node12"
  main: "main.js"

branding:
  icon: "check-square"
  color: "green"
