name: Build and Release Go Project

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Set up environment
        run: |
          go env -w GOFLAGS="-mod=vendor"

      - name: Build the Go project
        run: |
          CGO_ENABLED=0 go build -ldflags="-w -s" -v -o app .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: app
